//
//  Copyright © Kalisten 2021-2024
//
// swiftlint:disable identifier_name

public enum SFSymbols {
    public static let avatarWarning = "person.crop.circle.badge.exclam"
    public static let activeNFTsError = "rectangle.stack.person.crop"
    public static let arrowRight = "arrow.right"
    public static let arrowDown = "arrow.down"
    public static let arrowUp = "arrow.up"
    public static let arrowCircle = "arrow.triangle.2.circlepath"
    public static let backward30 = "goforward.30"
    public static let boltFill = "bolt.horizontal.circle.fill"
    public static let bug = "ant.fill"
    public static let chartBar = "chart.bar"
    public static let chartBarFill = "chart.bar.fill"
    public static let chevron = "chevron.left"
    public static let chevronRight = "chevron.right"
    public static let checkmark = "checkmark"
    public static let checkmarkCircle = "checkmark.circle"
    public static let checkmarkFill = "checkmark.circle.fill"
    public static let checkmarkSquareFill = "checkmark.square.fill"
    public static let chevronFill = "chevron.left.circle.fill"
    public static let circle = "circle"
    public static let circuit = "repeat"
    public static let close = "xmark"
    public static let circleFill = "circlebadge.fill"
    public static let claim = "arrow.down.circle.fill"
    public static let closeCircle = "xmark.circle"
    public static let closeFill = "xmark.circle.fill"
    public static let cooldown = "thermometer.snowflake"
    public static let copy = "square.on.square"
    public static let down = "chevron.down"
    public static let downFill = "chevron.down.circle.fill"
    public static let edit = "pencil"
    public static let email = "envelope.fill"
    public static let error = "exclamationmark.octagon"
    public static let errorFill = "exclamationmark.octagon.fill"
    public static let exclamationMark = "exclamationmark"
    public static let exercise = "biceps"
    public static let eye = "eye.fill"
    public static let eyeCrossed = "eye.slash.fill"
    public static let featureMissing = "gear"
    public static let filters = "slider.horizontal.3"
    public static let finishFlag = "flag.fill"
    public static let flowchart = "flowchart"
    public static let flowchartFill = "flowchart.fill"
    public static let forward30 = "gobackward.30"
    public static let `import` = "arrow.down.circle.fill"
    public static let info = "info.circle.fill"
    public static let globe = "globe"
    public static let house = "house"
    public static let houseFill = "house.fill"
    public static let minusCirckeFill = "minus"
    public static let multiply = "multiply"
    public static let pause = "pause.fill"
    public static let person = "person.crop.circle"
    public static let profile = "person.crop.square"
    public static let profileFill = "person.crop.square.fill"
    public static let play = "play.fill"
    public static let deleteAccount = "person.crop.circle.badge.xmark"
    public static let levelUp = "arrow.up.circle.fill"
    public static let optionsMenu = "ellipsis"
    public static let other = "questionmark.circle"
    public static let personFill = "person.fill"
    public static let plus = "plus"
    public static let power = "power"
    public static let plusFill = "plus.circle.fill"
    public static let qualityFeedback = "wand.and.stars.inverse"
    public static let radioButton = "largecircle.fill.circle"
    public static let resultsError = "waveform.badge.exclamationmark"
    public static let restore = "bolt.circle.fill"
    public static let reveal = "person.circle.fill"
    public static let save = "square.and.arrow.down"
    public static let sets = "list.bullet"
    public static let settings = "gear"
    public static let search = "magnifyingglass"
    public static let searchCircle = "magnifyingglass.circle"
    public static let searchCircleFill = "magnifyingglass.circle.fill"
    public static let share = "square.and.arrow.up"
    public static let skip = "forward.end.fill"
    public static let slotLocked = "lock.fill"
    public static let slotUnlocked = "lock.open.fill"
    public static let square = "square"
    public static let squareFill = "square.fill"
    public static let star = "star.fill"
    public static let stopwatch = "stopwatch"
    public static let store = "cart.fill"
    public static let timer = "timer"
    public static let trash = "trash.fill"
    public static let turnDown = "arrow.uturn.down"
    public static let unknown = "questionmark.circle.fill"
    public static let up = "chevron.up"
    public static let unlockSlot = "lock.circle.fill"
    public static let walletError = "creditcard.trianglebadge.exclamationmark"
    public static let walletLink = "link"
    public static let wrongContent = "text.badge.xmark"
    public static let one = "1.square"
    public static let oneFill = "1.square.fill"
    public static let two = "2.square"
    public static let twoFill = "2.square.fill"
    public static let three = "3.square"
    public static let threeFill = "3.square.fill"
    public static let four = "4.square"
    public static let fourFill = "4.square.fill"

    public static func levelUp(level: Int) -> String {
        "\(level).circle.fill"
    }
}
